#!/bin/sh

# This shell script builds pdf2htmlEX

# source ./buildScripts/reSourceVersionEnvs
. ./buildScripts/reSourceVersionEnvs

echo ""
echo "-------------------------------------------------------------------"
echo "BUILDING pdf2htmlEX (using gcc)"
echo "  PDF2HTMLEX_VERSION = [$PDF2HTMLEX_VERSION]"
echo "-------------------------------------------------------------------"

echo ""

set -ev

cd pdf2htmlEX
rm -rf build
mkdir build
cd build
GLIB_CFLAGS=$(pkg-config --cflags glib-2.0)
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$PDF2HTMLEX_PREFIX \
      -DCMAKE_C_FLAGS="$GLIB_CFLAGS" \
      -DCMAKE_CXX_FLAGS="$GLIB_CFLAGS" \
      ..
make $MAKE_PARALLEL
